export const ServicesData = [
  {
    title: "Eco Cleaning",
    path: "eco-cleaning",
    priceBefore: 120.0,
    priceAfter: 250.0,
    rating: "3.0",
    time: "2-3 hours",
    pic: "/imgs/srvs2.jpg",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    features: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
      "",
    ],
    process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
    offers: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    user_pic: "",
    user_title: "Buyer",
    user_name: "Emily & John Smith",
    user_text:
      "I found my ideal home in no time! The listings were detailed, the photos were accurate, and the whole process felt seamless. Customer service was top-notch, answering all my questions. I will definitely use this platform again in the future!",
  },
  {
    title: "Deep Cleaning",
    path: "deep-cleaning",

    priceBefore: 120.0,
    priceAfter: 250.0,
    rating: "3.0",
    time: "2-3 hours",
    pic: "/imgs/srvs2.jpg",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    features: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
      "",
    ],
    process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
    offers: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    user_pic: "",
    user_title: "Buyer",
    user_name: "Emily & John Smith",
    user_text:
      "I found my ideal home in no time! The listings were detailed, the photos were accurate, and the whole process felt seamless. Customer service was top-notch, answering all my questions. I will definitely use this platform again in the future!",
  },
  {
    title: "Renovation Cleaning",
    path: "renovation-cleaning",

    priceBefore: 120.0,
    priceAfter: 250.0,
    rating: "3.0",
    time: "2-3 hours",
    pic: "/imgs/srvs3.jpg",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    features: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
      "",
    ],
    process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
    offers: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    user_pic: "",
    user_title: "Buyer",
    user_name: "Emily & John Smith",
    user_text:
      "I found my ideal home in no time! The listings were detailed, the photos were accurate, and the whole process felt seamless. Customer service was top-notch, answering all my questions. I will definitely use this platform again in the future!",
  },

  {
    title: "Move in/ Move out",
    path: "move-in-move-out",

    priceBefore: 120.0,
    priceAfter: 250.0,
    rating: "3.0",
    time: "2-3 hours",
    pic: "/imgs/srvs4.jpg",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    features: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
      "",
    ],
    process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
    offers: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    user_pic: "",
    user_title: "Buyer",
    user_name: "Emily & John Smith",
    user_text:
      "I found my ideal home in no time! The listings were detailed, the photos were accurate, and the whole process felt seamless. Customer service was top-notch, answering all my questions. I will definitely use this platform again in the future!",
  },
  {
    title: "Move in/ Move out",
    path: "move-in-move-out",

    priceBefore: 120.0,
    priceAfter: 250.0,
    rating: "3.0",
    time: "2-3 hours",
    pic: "/imgs/srvs4.jpg",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    features: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
      "",
    ],
    process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
    offers: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    user_pic: "",
    user_title: "Buyer",
    user_name: "Emily & John Smith",
    user_text:
      "I found my ideal home in no time! The listings were detailed, the photos were accurate, and the whole process felt seamless. Customer service was top-notch, answering all my questions. I will definitely use this platform again in the future!",
  },
  {
    title: "Move in/ Move out",
    path: "move-in-move-out",

    priceBefore: 120.0,
    priceAfter: 250.0,
    rating: "3.0",
    time: "2-3 hours",
    pic: "/imgs/srvs4.jpg",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    features: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
      "",
    ],
    process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
    offers: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    user_pic: "",
    user_title: "Buyer",
    user_name: "Emily & John Smith",
    user_text:
      "I found my ideal home in no time! The listings were detailed, the photos were accurate, and the whole process felt seamless. Customer service was top-notch, answering all my questions. I will definitely use this platform again in the future!",
  },
];
